### PR TITLE
Groups-{cmn-Hans,eng}.md: terms updated

### PR DESCRIPTION
**Pull request by jyhi**
As per discussion.

### CODE REVIEW

**Comment by jyhi** [comment]
Please have a final review before merging!

**Comment by ecwu** [comment]
So far so good.

**Review by ecwu — APPROVED** [review]

**Comment by billzhonggz** [comment]
So far so good.

**Comment by jyhi** [comment]
Do not merge. There are still bugs being spotted.

**Comment by jyhi** [comment]
Merging.

**Pull request merged**
